title: tstrait manual
author: tskit developers
copyright: "2023"
only_build_toc_files: true

repository:
  url: https://github.com/daikitag/tstrait
  branch: main
  path_to_book: docs

html:
  use_repository_button: true

sphinx:
  extra_extensions:
  - sphinx.ext.autodoc
  - sphinx.ext.autosummary
  - sphinx.ext.todo
  - sphinx.ext.viewcode
  - sphinx.ext.intersphinx
  - sphinx_issues
  - sphinxarg.ext
  - IPython.sphinxext.ipython_console_highlighting  

  config:
    myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath

    intersphinx_mapping:
      python: ["https://docs.python.org/3/", null]
      tskit: ["https://tskit.dev/tskit/docs/stable/", null]
      tskit-tutorials: ["https://tskit.dev/tutorials/", null]
      msprime: ["https://tskit.dev/msprime/docs/stable/", null]
      stdpopsim: ["https://stdpopsim.readthedocs.io/en/stable", null]
      numpy: ["https://numpy.org/doc/stable/", null]

    todo_include_todos: true

    nitpicky: true
    
    autodoc_member_order: bysource

    bibtex_reference_style: author_year