name: Docs

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'

env:
  BUILD_GSL: true
  COMMIT_EMAIL: ben.jeffery.well+adminbot@gmail.com
  OWNER: tskit-dev
  REPO: tstrait

jobs:
  build-deploy-docs:
    name: Docs
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"

      - uses: actions/cache@v4.2.0
        id: venv-cache
        with:
          path: venv
          key: docs-venv-v1-${{ hashFiles('requirements/CI-docs/requirements.txt') }}

      - name: Create venv and install deps
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip wheel
          pip install -r requirements/CI-docs/requirements.txt

      - name: Build Docs
        run: |
          . venv/bin/activate
          cd docs
          make

      - name: Trigger docs site rebuild
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST https://api.github.com/repos/tskit-dev/tskit-site/dispatches \
                    -H 'Accept: application/vnd.github.everest-preview+json' \
                    -u AdminBot-tskit:${{ secrets.ADMINBOT_TOKEN }} \
                    --data '{"event_type":"build-docs"}'
